# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Nikhil Thota
email: nthota92@gmail.com
description: > # this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://nikhilthota.com" # the base hostname & protocol for your site, e.g. http://example.com
linkedin_username: nikhil-thota-ab2731104
github_username:  nt92

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

collections:
  projects:
    output: true
    permalink: /projects/:path/
  work:
    output: true
    permalink: /work/:path/
  education:
    output: true
    permalink: /education/:path/
  extracurricular:
    output: true
    permalink: /extracurricular/:path/
